# GitHub Secret Scanning Configuration
# Excludes test files with dummy credentials from secret scanning alerts

paths-ignore:
  - 'apps/api/src/__tests__/**'
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/test-fixtures/**'
